CREATE DATABASE DMD;

-- CREATE AMP TABLE
CREATE TABLE AMP (
    `APID` BIT  NOT NULL,
    `INVALID` BIT  NULL,
    `VPID` BIT  NOT NULL,
    `NM` VARCHAR (255) NOT NULL,
    `ABBREVNM` VARCHAR (255) NULL,
    `DESC` VARCHAR (255) NOT NULL,
    `NMDT` DATETIME  NULL,
    `NM_PREV` VARCHAR (255) NULL,
    `SUPPCD` BIT  NOT NULL,
    `LIC_AUTHCD` BIT  NOT NULL,
    `LIC_AUTH_PREVCD` BIT  NULL,
    `LIC_AUTHCHANGECD` BIT  NULL,
    `LIC_AUTHCHANGEDT` DATETIME NULL,
    `COMBPRODCD` BIT  NULL,
    `FLAVOURCD` BIT  NULL,
    `EMA` BIT  NULL,
    `PARALLEL_IMPORT` BIT  NULL,
    `AVAIL_RESTRICTCD` BIT  NOT NULL
);

-- CREATE AP_ING TABLE
CREATE TABLE AP_ING (
    `APID` BIT  NOT NULL,
    `ISID` BIT  NOT NULL,
    `STRNTH` real NULL,
    `UOMCD` BIT  NULL
);

-- CREATE LIC_ROUTE TABLE
CREATE TABLE LIC_ROUTE (
    `APID` BIT  NOT NULL,
    `ROUTECD` BIT  NOT NULL
);

-- CREATE AP_INFO TABLE
CREATE TABLE AP_INFO (
    `APID` BIT  NOT NULL,
    `SZ_WEIGHT` VARCHAR (8000)  NULL,
    `COLOURCD` BIT  NULL,
    `PROD_ORDER_NO` VARCHAR (8000) NULL
);

-- CREATE AMPP TABLE
CREATE TABLE AMPP (
    `APPID` BIT  NOT NULL,
    `INVALID` BIT  NULL,
    `NM` VARCHAR (8000)  NOT NULL,
    `ABBREVNM` VARCHAR (8000)  NULL,
    `VPPID` BIT  NOT NULL,
    `APID` BIT  NOT NULL,
    `COMBPACKCD` BIT  NULL,
    `LEGAL_CATCD` BIT  NOT NULL,
    `SUBP` VARCHAR (8000)  NULL,
    `DISCCD` BIT  NULL,
    `DISCDT` DATETIME  NULL
);

-- CREATE PACK_INFO TABLE
CREATE TABLE PACK_INFO (
    `APPID` BIT  NOT NULL,
    `REIMB_STATCD` BIT  NOT NULL,
    `REIMB_STATDT` DATETIME  NULL,
    `REIMB_STATPREVCD` BIT  NULL,
    `PACK_ORDER_NO` VARCHAR (8000) NULL
);

-- CREATE PRESCRIB_INFO TABLE
CREATE TABLE PRESCRIB_INFO (
    `APPID` BIT  NOT NULL,
    `SCHED_2` BIT  NULL,
    `ACBS` BIT  NULL,
    `PADM` BIT  NULL,
    `FP10_MDA` BIT  NULL,
    `SCHED_1` BIT  NULL,
    `HOSP` BIT  NULL,
    `NURSE_F` BIT  NULL,
    `ENURSE_F` BIT  NULL,
    `DENT_F` BIT  NULL
);

-- CREATE PRICE_INFO TABLE
CREATE TABLE PRICE_INFO (
    `APPID` BIT  NOT NULL,
    `PRICE` BIT  NULL,
    `PRICEDT` DATETIME  NULL,
    `PRICE_PREV` BIT  NULL,
    `PRICE_BASISCD` BIT  NOT NULL
);

-- CREATE REIMB_INFO TABLE
CREATE TABLE REIMB_INFO (
    `APPID` BIT  NOT NULL,
    `PX_CHRGS` BIT  NULL,
    `DISP_FEES` BIT  NULL,
    `BB` BIT  NULL,
    `LTD_STAB` BIT  NULL,
    `CAL_PACK` BIT  NULL,
    `SPEC_CONTCD` BIT  NULL,
    `DND` BIT  NULL,
    `FP34D` BIT  NULL
);

-- CREATE ING TABLE
CREATE TABLE ING (
    `ISID` BIT  NOT NULL,
    `ISIDDT` DATETIME  NULL,
    `ISIDPREV` BIT  NULL,
    `INVALID` BIT  NULL,
    `NM` VARCHAR (8000) NOT NULL
);

-- CREATE INFO TABLE
CREATE TABLE INFO (
    `CD` BIT  NOT NULL,
    `DESC` VARCHAR (8000) NOT NULL
);

-- CREATE VMP TABLE
CREATE TABLE VMP (
    `VPID` BIT  NOT NULL ,
    `VPIDDT` DATETIME  NULL ,
    `VPIDPREV` BIT  NULL ,
    `VTMID` BIT  NULL ,
    `INVALID` BIT  NULL ,
    `NM` VARCHAR (8000)  NOT NULL ,
    `ABBREVNM` VARCHAR (8000)  NULL ,
    `BASISCD` BIT  NOT NULL ,
    `NMDT` DATETIME  NULL ,
    `NMPREV` VARCHAR (8000)  NULL ,
    `BASIS_PREVCD` BIT  NULL ,
    `NMCHANGECD` BIT  NULL ,
    `COMBPRODCD` BIT  NULL ,
    `PRES_STATCD` BIT  NOT NULL ,
    `SUG_F` BIT  NULL ,
    `GLU_F` BIT  NULL ,
    `PRES_F` BIT  NULL ,
    `CFC_F` BIT  NULL ,
    `NON_AVAILCD` BIT  NULL ,
    `NON_AVAILDT` DATETIME  NULL ,
    `DF_INDCD` BIT  NULL ,
    `UDFS` real  NULL ,
    `UDFS_UOMCD` BIT  NULL ,
    `UNIT_DOSE_UOMCD` BIT  NULL
);

-- CREATE ONT TABLE
CREATE TABLE ONT (
    `VPID` BIT  NOT NULL,
    `FORMCD` BIT  NOT NULL
);

-- CREATE VPI TABLE
CREATE TABLE VPI (
    `VPID` BIT  NOT NULL,
    `ISID` BIT  NOT NULL,
    `BASIS_STRNTCD` BIT  NULL,
    `BS_SUBID` BIT  NULL,
    `STRNT_NMRTR_VAL` real  NULL,
    `STRNT_NMRTR_UOMCD` BIT  NULL,
    `STRNT_DNMTR_VAL` real  NULL,
    `STRNT_DNMTR_UOMCD` BIT  NULL
);

-- CREATE DFORM TABLE
CREATE TABLE DFORM (
    `VPID` BIT  NOT NULL,
    `FORMCD` BIT  NOT NULL
);

-- CREATE CONTROL_INFO TABLE
CREATE TABLE CONTROL_INFO (
    `VPID` BIT  NOT NULL,
    `CATCD` BIT  NOT NULL,
    `CATDT` DATETIME  NULL,
    `CAT_PREVCD` BIT  NULL
);

-- CREATE DROUTE TABLE
CREATE TABLE DROUTE (
    `VPID` BIT  NOT NULL,
    `ROUTECD` BIT  NOT NULL
);

-- CREATE VMPP TABLE
CREATE TABLE VMPP (
    `VPPID` BIT NOT NULL,
    `INVALID` BIT NULL,
    `NM` VARCHAR (8000) NOT NULL,
    `ABBREVNM` VARCHAR (8000) NULL,
    `VPID` BIT NOT NULL,
    `QTYVAL` real NOT NULL,
    `QTY_UOMCD` BIT NOT NULL,
    `COMBPACKCD` BIT NULL
);

-- CREATE DTINFO TABLE
CREATE TABLE DTINFO (
    `VPPID` BIT NOT NULL,
    `PAY_CATCD` BIT NOT NULL,
    `PRICE` BIT NULL,
    `DT` DATETIME NULL,
    `PREVPRICE` BIT NULL
);

-- CREATE CCONTENT TABLE
CREATE TABLE CCONTENT (
    `PRNTVPPID` BIT NOT NULL,
    `CHLDVPPID` BIT NOT NULL
);

-- CREATE VTM TABLE
CREATE TABLE VTM (
    `VTMID` BIT  NOT NULL,
    `INVALID` BIT  NULL,
    `NM` VARCHAR (8000) NOT NULL,
    `ABBREVNM` VARCHAR (8000)  NULL,
    `VTMIDPREV` VARCHAR (8000)  NULL,
    `VTMIDDT` DATETIME  NULL
);
